### PR TITLE
Create the Occurrence Screen

### LINKED ISSUE #23: Viewing, editing and deleting events registered by the user
## Issue Description
List all the occurrences that a user has, each row/card should show all informations (register_date, type, ...), show edit and delete button.
The update of the occurrence should use the create screen or a similar screen. (verify with the api if the update has some kind of limitation to old occurrences). If an occurrence is updated, the list should update to the new data.
The deletion of an occurrence should open a confirmation modal to the user, the deletion should only proceed if the user confirm. If the occurrence is successfully deleted, it should remove the row/card from the list.

## Tasks:
- [x] Create the list of occurrences.
- [x] Refactor or create a screen to update the information of an occurrence.
- [x] Create a function to delete an occurrence.
- [x] Update the list after update/delete.

### PR DESCRIPTION
**Pull request by tsrrodrigues**
## Issue #
Resolves #23 

## Description
This PR creates the Occurrences screen that show to the user his occurrences. It shows a preview on a card and the user can click to edit/view the details of the occurrence. It it possible to delete the occurrence as well. For the edit/view page it was used the Occurrence component that already exists. It was modified so that the component can register a new occurrence or edit an existing one. 

## Screenshots (if appropriate):
image

image

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## How to validate?

It is necessary to add the page on navigation somehow. And ignore the icon for the page on navbar, it was used just for test. After this test if the occurrences shows correctly on both pages and if you can edit an existing occurrence.

### CODE REVIEW

**Comment by tsrrodrigues** [comment]
Ainda irei arrumar o estilo do código, os reviewers podem revisar sem problemas, só irei dar o merge após consertar o estilo.

**Comment by alvesitalo** [comment]
Now, navigation.setParams({ occurrence: null }) is no longer causing problems after unfocusing screen.

**Comment by lboaventura25** [comment]
When user delete an occurrence, the occurrence stay on list. Maybe it is a good idea make a filter on handle delete function to delete the occurrence from list that is show.

**Review by silvasara — APPROVED** [review]
If it is not possible to make this correction suggested by @lboaventura25  by the end of Sprint 6, please create a bugfix issue for the problem

**Review by renan601 — APPROVED** [review]

**Pull request merged**
