### PR TITLE
Adding all screens to Bottom Tab Bar

### PR DESCRIPTION
**Pull request by alvesitalo**
## Issue #

None

## Description

Add all screens to bottom tab and creates initial logic for reporting a occurrence on Home screen.

## Checklist:

- [x] My code follows the code style of this project.

## How to validate?

Testing the app and watching Tab Bar's behavior

### CODE REVIEW

**Review by silvasara — COMMENTED** [review]
the application has some errors:
image

**Review by silvasara — CHANGES_REQUESTED** [review]
Where's the login screen?
The profile display and editing screen is being displayed even if you are not logged in.
The delete account and sign out button are also displayed without being logged in
The occurrence button is not leading anywhere.
Please update the branch with develop.

**Comment by lboaventura25** [comment]
Corrections were made. If user clicks on occurrence button without being logged will show the modal, but if user is logged it will go to Home screen. On issue #21 the correct flow of occurrence register will be completed.

**Review by silvasara — APPROVED** [review]

**Review by renan601 — APPROVED** [review]

**Comment by alvesitalo** [comment]
Thanks @lboaventura25.

**Pull request merged**
