### PR TITLE
Add About Screen

### LINKED ISSUE #113: Fill app text screens
## Issue Description
Fill in the screen "Sobre" with information about the application and the context in which it was developed.

On the "Ajuda" screen, make the guide appear, just as it appears when you start the application for the first time.

## How it will be validated
To validate the issue the following tests will be done:

* The reviewer will check the "Sobre" screen and review the text contained in it
* The reviewer will check the "Ajuda" screen and see if the application guide appears and work properly

If the tests are successful, the issue will be considered ready.

### PR DESCRIPTION
**Pull request by alvesitalo**
## Issue 
Resolves #113 

## Description

Adds a About app screen and links Tutorial screen to "Ajuda" option on Settings. Also, the app splash screen was updated.

## Screenshots (if appropriate):

photo5089420337933822109

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## How to validate?

1. Go to Settings screen;
2. Click on "Ajuda" or "Sobre" option.

### CODE REVIEW

**Comment by silvasara** [comment]
@alvesitalo Please, solve the ESLint problems and update the branch with develop

**Review by silvasara — COMMENTED** [review]
@alvesitalo Please, solve the ESLint problems and update the branch with develop

**Comment by alvesitalo** [comment]
Hi @silvasara, I need PR #120 to be merged first, or there will be more conflicts.

**Review by silvasara — APPROVED** [review]

**Comment by tsrrodrigues** [comment]
In my screen the word "que" on the 2º line in the 2º paragraph does not appears. And the word "estatísticas" is misspelled.
image

**Review by lboaventura25 — APPROVED** [review]

**Pull request merged**
